apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: docker-registry.demo.axway.com/apac-ci-images/api-gateway-defaultgroup:DEV.8.14.2 
  imagePullSecrets:
  - name: axway-registry 
