apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.anm.name }}
  name: {{ .Values.anm.name }}-ext
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.anm.serviceType }}
  selector:
    app: {{ .Values.anm.name }}
  ports:
  - port: {{ .Values.anm.trafficPort }}
    protocol: TCP
    targetPort: {{ .Values.anm.targetPort }}
