{{- if eq .Values.apimgmt.extenabled true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.apimgmt.name }}
  name: {{ .Values.apimgmt.name }}-ext
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.apimgmt.serviceType }}
  selector:
    app: {{ .Values.apimgmt.name }}
  ports:
  - port: {{ .Values.apimgmt.trafficPort }}
    protocol: TCP
    targetPort: {{ .Values.apimgmt.targetPort }}
 # sessionAffinity: ClientIP
{{- end }}
